server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tradebridge
    username: postgres
    password: P@ssw0rd2025
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

# Location Data Initialization Configuration
app:
  initialize:
    locations: true
    locations.async: true